package me.axolotl.api.sql.interfaces;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * The BaseDB interface defines the basic operations for connecting to and disconnecting from a database.
 *
 * @since 2024-02-22
 */
public interface BaseDB {

    /**
     * The default JDBC link.
     */
    String defaultLink = "jdbc:";

    /**
     * The JDBC link for SQLite databases.
     */
    String SQLiteLink = "jdbc:sqlite:";

    /**
     * Establishes a connection to the database.
     *
     * @throws SQLException if a database access error occurs
     */
    void connect() throws SQLException;

    /**
     * Closes the connection to the database.
     *
     * @throws SQLException if a database access error occurs
     */
    void disconnect() throws SQLException;

    /**
     * Executes a non-query SQL command on the database.
     *
     * @param command the SQL command to be executed
     * @throws SQLException if a database access error occurs or the SQL command fails to execute
     */
    void runNormal(String command) throws SQLException;

    /**
     * Executes a SQL query command on the database and returns the resulting ResultSet.
     *
     * @param command the SQL command to be executed
     * @return the ResultSet generated by the execution of the SQL command
     * @throws SQLException if a database access error occurs or the SQL command fails to execute
     */
    ResultSet runSearch(String command) throws SQLException;

}
